# Generated by Django 5.0 on 2023-12-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=8)),
                ('output_path', models.CharField(max_length=255)),
                ('selected_values', models.JSONField()),
            ],
        ),
    ]
