# Generated by Django 5.0 on 2023-12-16 09:40

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('mastertemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 16, 0, 0)),
            preserve_default=False,
        ),
    ]
