# Generated by Django 5.0 on 2023-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastertemplate', '0002_auto_20231216_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
