# Generated by Django 5.0 on 2023-12-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastertemplate', '0004_processeddata_duration_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='duration_of_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
