# Generated by Django 5.0 on 2023-12-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastertemplate', '0005_alter_processeddata_duration_of_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_version', models.CharField(max_length=255)),
                ('edited_by', models.CharField(max_length=255)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('duration_of_update', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
