# Generated by Django 5.0 on 2023-12-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastertemplate', '0006_sheetupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetupdate',
            name='edited_sheets',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sheetupdate',
            name='workbook_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
