# Generated by Django 5.0 on 2024-01-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastertemplate', '0007_sheetupdate_edited_sheets_sheetupdate_workbook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='unique_id',
            field=models.CharField(max_length=50),
        ),
    ]
