# Generated by Django 5.0 on 2023-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheckRecord',
            fields=[
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=100)),
                ('num_records', models.IntegerField()),
                ('date_of_processing', models.DateField()),
                ('qc_processing_time', models.IntegerField()),
                ('qc_done_by', models.CharField(max_length=100)),
            ],
        ),
    ]
