# Generated by Django 5.0 on 2023-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheckrecord',
            name='date_of_processing',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
